### PR TITLE
Add support for the AMPL language

### PR DESCRIPTION
**Pull request by vitaut**
The proposed PR adds support for the AMPL language (http://en.wikipedia.org/wiki/AMPL). AMPL is a popular language for mathematical programming (optimization). Currently AMPL code is incorrectly reported as Modula-2 code on Ohloh, see here: https://www.ohloh.net/forums/10/topics/8617?page=1#posts-25355

### CODE REVIEW

**Comment by notalex** [comment]
Thanks @vitaut for your work. I apologize for the late response. There are some minor fixes required in this PR. The work has conflicts with master, these must be resolved. Also, multiline ampl comments are being recognized as code.

**Comment by vitaut** [comment]
Thanks for getting back to me but unfortunately I don't have time to work on this anymore.

**Comment by notalex** [comment]
We were able to build up on your work and detect AMPL files correctly in #50. Thank you for your contribution.

**Comment by vitaut** [comment]
Cool, thanks!

**Pull request closed without merging**
