### PR TITLE
Add support for new language Mathematica

### PR DESCRIPTION
**Pull request by eschnett**
I implemented support for detecting Mathematica as new language. I added a test case as well.

### CODE REVIEW

**Comment by ianhinder** [comment]
Is further work needed for this to be merged?  The respective projects still show up incorrectly on OpenHub as being in Objective C rather than in Mathematica.

**Comment by eschnett** [comment]
I'm not aware of further work being necessary. I didn't receive any feedback on the implementation. It may be necessary to rebase the implementation, now after two years of silence.

**Comment by notalex** [comment]
@eschnett, sorry for the late response. I can help get this merged. This PR needs a little more work with tests. In addition to the file **test/expected_dir/mathematica1.m**, one needs to add another file at **test/src_dir/mathematica1.m** which reflects the **expected_dir** file minus the **mathematica ...** prefixes. This will enable the **test/unit/parser.h** test to compare the mathematica parser results.

**Comment by notalex** [comment]
I have tried adding the **test/src_dir/mathematica1.m** file and found that the tests fail on file detection. The mathematica files are being detected as objective_c. This is due to a flaw in existing master code. This [new PR](https://github.com/blackducksoftware/ohcount/pull/47) fixes the problem. After making this change, I found that the tests fail on mathematica comment lines being incorrectly counted as code.

**Pull request merged**
