### PR TITLE
Add definition for Modelica language

### PR DESCRIPTION
**Pull request by sjoelund**
Language definition: https://modelica.org
Grammar: http://modelica.github.io/Modelica/help/ModelicaReference.ModelicaGrammar.html

### CODE REVIEW

**Comment by thorade** [comment]
@blackducksoftware Could you comment on why this is not getting merged?

**Comment by dietmarw** [comment]
Please merge ASAP

**Comment by thorade** [comment]
The link to the grammar is currently broken, where is the new location?

**Comment by tbeu** [comment]
http://doc.modelica.org/om/ModelicaReference.ModelicaGrammar.html

**Comment by dietmarw** [comment]
http://doc.modelica.org/om/ModelicaReference.ModelicaGrammar.html

**Comment by tbeu** [comment]
Modelica language support is required for a proper language statistics on https://www.openhub.net/p/Modelica

**Pull request merged**
